### ISSUE TITLE
Could you include an example of how to include the library as a <dependency> in the POM file?

### ISSUE THREAD

**Issue by charleswhchan** [aled/jsi#34]
I tried to add the following to the pom.xml

```
<repositories>
  <repository>
    <id>jsi.sourceforge.net</id>
    <name>sourceforge jsi repository</name>
    <url>http://sourceforge.net/projects/jsi/files/m2_repo</url>
  </repository>
</repositories> 

<dependency>
  <groupId>net.sourceforge.jsi</groupId>
  <artifactId>jsi</artifactId>
  <version>1.0.0</version>
</dependency>
```

and I received the following error: "The POM for net.sourceforge.jsi:jsi:jar:1.0.0 is missing, no dependency information available"

Thanks!

**Comment by akpmp** [comment]
Hi 
how to build sciknowmineProject submodule
please help me

Thanks

**Comment by akpmp** [comment]
Hi
 I have run sciKnowMine repository using command 
java -classpath target/skmTriage-1.1.5-SNAPSHOT-jar-with-dependencies.jar edu.isi.bmkeg.skm.triage.bin.AddPmidsToTriageCodes
after running this command given some out put
arguments: <pmidCodeFile> <newPmidFile> <newCode> [overwrite?]
what is <pmidCodeFile> <newPmidFile> <newCode>
please help me

Thanks
