### ISSUE TITLE
Indexing just Points

### ISSUE THREAD

**Issue by cbobed** [aled/jsi#37]
Hi, 

I've been searching an implementation of RTree's to perform some tests of a prototype, but I've seen that it is not directly allowed to add just points to the RTree. I've made a workaround that seems to work by adding "one-dimensional rectangles" :P, but am I missing anything? Why aren't Points allowed to be added directly (at least in this implementation - I've seen others that allowed me to do so)? 

Thank you in advance

**Comment by aled** [comment]
Using rectangles with the min and max coordinates set to the same value works fine (as you have found).  

You could write an Add() method that takes a point (but adds a rectangle) if you like, and send a pull request. Actually storing points in the underlying data structures was never implemented as the performance was already sufficient for the original application.
