### ISSUE TITLE
Is there an attribute or method to write complete hierarchy?

### ISSUE THREAD

**Issue by sanketkumarsingh** [aled/jsi#39]
Hi,

Thank you for the implementation.

I am trying to use R Tree implementation here and I have to write the hierarchy created on file so that I can further visualize containment relationship of spatial points. Is there an attribute or method that returns object which I can write to file. 

Please suggest.

Thanks

**Comment by aled** [comment]
Hi, unfortunately there is currently no method that does that, sorry.
