### ISSUE TITLE
Error using RTree

### ISSUE THREAD

**Issue by mvalero09** [aled/jsi#41]
Hi,

I have an issue when I use an object of type RTree, I store my SpatialIndex in a redis cache like a string (format JSON), I recovery this and cast from json to RTree class, I initialize it with the init method and when I try to add a new rectangle to the index by twice I receive a nullpointer in the choosenode method, exactly in this part:

    Node n = getNode(rootNodeId); (RTree.class -> chooseNode)

I lose values of nodeMap and rootNodeId, I can see debugging it.

I think this problem is because in redis I store it like a string and then I convert this one to RTree class but it's the only way I have to do that.

There is a different way to use this type of objects?

Thanks!

**Comment by aled** [comment]
Can you post your serialization code?

**Comment by mvalero09** [comment]
In this part of code y initialize and use the spatialIndex

![image](https://user-images.githubusercontent.com/48031501/53764260-8a2c4e80-3eab-11e9-834d-126f05a525cf.png)

And of that way y store and catch this one from redis

![image](https://user-images.githubusercontent.com/48031501/53764306-a92ae080-3eab-11e9-88e8-964a7e27cce6.png)

**Comment by aled** [comment]
I don't know much about GSON, but as far as I can tell, it doesn't work with generics.

Pretty sure you'd have to write custom serialization code for this to work.
