### ISSUE TITLE
RTree appears to not be threadsafe across reads

### ISSUE THREAD

**Issue by jerryplin** [aled/jsi#42]
Thanks for the great library -- the indexing is fast and the library seems promising for our purposes.

It appears that RTree is not thread-safe across reads. I have multiple threads calling contains, and I get these stack traces:

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at gnu.trove.TIntArrayList.get(TIntArrayList.java:240)
        at gnu.trove.TIntArrayList.remove(TIntArrayList.java:380)
        at gnu.trove.TIntStack.pop(TIntStack.java:69)
        at com.infomatiq.jsi.rtree.RTree.contains(RTree.java:600)

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
        at gnu.trove.TIntArrayList.get(TIntArrayList.java:240)
        at gnu.trove.TIntStack.peek(TIntStack.java:78)
        at com.infomatiq.jsi.rtree.RTree.contains(RTree.java:566)

When I synchronize the RTree instance before calling contains, I do not get the exceptions (which seem repeatable when not synchronized).

Do you expect RTree to be threadsafe across reads?

**Comment by aled** [comment]
Well. Depends a bit which version you're on. Version 1.0.0 (as linked on sourceforge) is definitely not threadsafe and the behaviour you describe is as expected. 

However it would be trivial to make it threadsafe for reads by declaring local variables (parents and parentsEntry, maybe others) in the Contains method. In fact looking at the master branch on github, that change is already in it. Maybe try that version and see what happens?

**Comment by jerryplin** [comment]
Thanks for your quick response! Yes, it appears that version 1.1.0 is threadsafe across reads. (I did need to upgrade the Trove library to version 3 for the newer version of RTree.)
